<a href="https://colab.research.google.com/github/rfahreza/Analisis-Sentimen-My-UNP/blob/main/Scraping_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Step of Scraping Data

Scraping data review and rating in My UNP app from Google Play Store

In [1]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 3.0 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [4]:
from google_play_scraper import app, reviews, Sort

# Fetch app details
app_details = app('com.unp.newmyunp')  # Replace with the app's package name
print("App Title:", app_details['title'])
print("Rating:", app_details['score'])
print("Total Reviews:", app_details['reviews'])

# Fetch reviews
result, continuation_token = reviews(
    'com.unp.newmyunp',  # Replace with the app's package name
    lang='id',          # Language (e.g., 'en' for English)
    country='id',       # Country (e.g., 'us' for United States)
    sort=Sort.MOST_RELEVANT,  # Sorting: MOST_RELEVANT, NEWEST, etc.
    count=5000           # Number of reviews to fetch
)

# Print fetched reviews
for review in result:
    print(f"Review by {review['userName']}:")
    print(f"Rating: {review['score']}")
    print(f"Content: {review['content']}")
    print("=" * 100)

App Title: My UNP
Rating: None
Total Reviews: None
Review by dinda amalia:
Rating: 1
Content: jujur ribet bgt aplikasinya, lelet, kamera mirror, lokasi sering bgt jauh dari lokasi, kan ga lucu ngulang matkul krn aplikasi sering error gini. mending balik ke e-learning lagi aja min, udh bener pake 1 web aja buat ngumpulin tugas+absen. aslinya mau ngasih bintang -999999, tapi ga ada di opsi.
====================================================================================================
Review by Akami Sayuri:
Rating: 1
Content: Saran saya, harusnya di uji coba dulu baru di resmikan. Soalnya ini masa kita mau absen ada yg keluar lah, nggak ke deteksi lah, nggak ke simpanlah, bahkan jadinya terlewat absen nya cuma karena masalah yang berasal dari apk nya. Bukan dari mahasiswa nya.
====================================================================================================
Review by Hamid Awaludin:
Rating: 1
Content: Mengecewakan. Sebaiknya sebelum diterapkan sistem pengambilan absen, lebih baik di uji coba terlebih dahulu. Untuk pengambilan absen membutuhkan waktu cukup lama untuk dapat pengambilan kehadiran, terkadang aplikasi mendeteksi kegiatan ilegal namun tidak ada kegiatan ilegal. Masalah jaringan sering terjadi pada aplikasi ini, jaringan tidak masalah. Pada aplikasi terkadang hanya blank saja. Untuk kedepannya sebaiknya di perbaiki dulu sistem nya sebelum digunakan.
====================================================================================================
Review by Jeise Gaming:
Rating: 1
Content: banyak bug tolong diperbaiki minnnnnnn, gabisa ambil absen malah notifikasi cek jaringan mulu dah, bukan cmn aku diang semua kelas ngalaminnnn, tolong segera diperbaiki atau balik lagi saja ke sistem e-learning seperti tahun kemarin
====================================================================================================
Review by Ahmad Nur Hafidz:
Rating: 1
Content: ada kesalahan dalam aplikasi yang membuat saya tidak bisa masuk aplikasi, dikarenakan itu error atau ada bug, sehingga saya tidak dapat mengakses untuk mengambil presensi, saran saya kembalikan saja ke e-learning yang dapat dengan mudah di akses
====================================================================================================
Review by Dini Putri Casandy:
Rating: 5
Content: kepada developer mohon untuk diperbaiki kembali aplikasi nya, karena banyak bug yang terjadi pada sistem saat ini.Hal ini membuat mahasiswa kesulitan untuk mengisi absen, dan ada pula dosen yang tidak mau tau terkait masalah bug ini, terima kasih
====================================================================================================
Review by Gina Sonia:
Rating: 1
Content: Aplikasinya keluar2 terus pas mau ngefoto buat absen, padahal jaringan bagus, penyimpanan banyak, blm lgi lokasinya ngk jelas bgt malah bikin perkuliahan ribetttt, blm lgi loadingnya lama bet woy, absen manual aja lah klo gitu
====================================================================================================
Review by Fatmadilla Adinda:
Rating: 1
Content: Aplikasinya lelet kali, bukannya mempermudah malah mempersulit. Terus kameranya landscape. Kalau ga iPhone ga bisa absen
====================================================================================================
Review by Cindy Marsya putri:
Rating: 1
Content: Banyak bug ,gabisa ambil absen malahan yg keluar notif terdeteksi aplikasi ilegal,absen juga harus di kelas gimana kalau lagi daring yg jarak rumhnya jauh dari kampus,lebih baik balik lagi ke e-learning seperti tahun sebelumnya
====================================================================================================
Review by Kira Queen:
Rating: 1
Content: masih banyaknya bug di aplikasi, sulit untuk login padahal user sudah benar namun dikatakan tidak ditemukan, susah mendapatkan lokasi dan fotonya mirror
====================================================================================================
Review by Alifa Beauty:
Rating: 1
Content: Di hp saya tidak bisa mengambil absensi, jadinya terpaksa meminjam hp teman, kenapa ya? Padahal di awal pemakaian apk saya sudah mengizinkan kamera, mikrofon dan juga lokasinya, tapi tetap saja tidak bisa
====================================================================================================
Review by Rizky Mahmudha:
Rating: 1
Content: Bintang 1 dulu deh kini Mohon diperbaiki lagi karena aplikasi nya susah dibuka dan mohon dipersiapkan lebih matang lagi sebelum diluncurkan aplikasi nya ya min, terimakasih
====================================================================================================
Review by MRadit al fauza:
Rating: 1
Content: aplikasi nya sangat tidak bagus , di karenakan pembukaan aplikasi nya yang lelet + foto untuk absen bersifat mirroring
====================================================================================================
Review by Dian Pramudita:
Rating: 2
Content: bintang 2 dulu, apknya udh keren tapi masih developt nih kurangnya.. semoga makin segera dikembangkan lagi masih ngebug soalnya. semangat myunp
====================================================================================================
Review by Ryanni Puspita:
Rating: 1
Content: Selalu keluar terus saat mau absen, bug nya bermasalah, setelah keluar baru ada tulisan lapor, mempersulit mahasiswa ini namanya, bukan mempermudah
====================================================================================================
Review by Arfan Fauzar:
Rating: 4
Content: Bagus... karena real tempat dan waktu 😉, tapi sayang pemberitahuan updatenya kadang silent, sehingga saat penggunaan agak kurang nyaman...
====================================================================================================
Review by Yaktinafi Salavia:
Rating: 2
Content: Setiap perkuliahan online saya tidak bisa isi presensi, scan wajahnya tidak muncul, tolong ditindaklanjuti
====================================================================================================
Review by Maya Desvina Putri:
Rating: 1
Content: Aplikasinya manja banget. Udah dibikin jadi aturan resmi, harus ini, harus itu. Nah sekarang ngga bisa dibuka. Nunggu loadingnya lama banget. Kek ngga diurus. Ngga jelas ni UNP. Mending di selesaiin dulu tuh e-learning baru bikin kebijakan baru. Ngeselin sumpah. "Barang siapa yang menyusahkan orang lain, ....." Isi sendiri dah. Jangankan dosen senior, mahasiswa pun juga pusing iniii dasar aplikasi ngga jelas
====================================================================================================
Review by M. Rama:
Rating: 3
Content: harus membutuhkan jaringan yang bagus untuk di operasikan..dan loding setiap pindah halaman agak lama
====================================================================================================
Review by lasart V:
Rating: 1
Content: Gimana mau ambil absen,home nya aja nggk muncul seakan² hilang sinyal,padahal jaringan lancar
====================================================================================================
Review by Helni Putri:
Rating: 1
Content: sangat buruk, perbaiki lagi. masa iya g bisa ngambil absen, serius? cuma IP yang bisa
====================================================================================================
Review by surya hafizh:
Rating: 2
Content: Aplikasiny sangat bagus. Saking bagusny nunggu pindah page lama sekali👌
====================================================================================================
Review by Tasya Putri pernama:
Rating: 1
Content: aplikasi nya jelek,lelet banget, pdahal jringan lancar,ga guna ni aplikasi
====================================================================================================
Review by Lutvizah Fitri:
Rating: 4
Content: Kenapa selalu berada di luar area ya min 73 meter katanya jd ga bisa absen
====================================================================================================
Review by Diki Almaqfirah:
Rating: 1
Content: Lelet masuknya dan banyak bug, tolong diperbaikin
====================================================================================================
Review by Awfa Zhillan manan:
Rating: 1
Content: seharusnya ada masa uji coba sebelum berpindah dari e-learning ke aplikasi sepenuhnya
====================================================================================================
Review by Naila Raisa:
Rating: 2
Content: tolong jangan sering bug, gk bisa dibuka
====================================================================================================
Review by Rangga Saputra:
Rating: 1
Content: kalau ada bintang -5 tak kasih dah. ya kali kan ngulang studi cuma karena gabisa absen👍
====================================================================================================
Review by Ann:
Rating: 1
Content: sangat sulit masuk ke apk pak, tolong diperbaiki
====================================================================================================
Review by Ja Ke0706:
Rating: 1
Content: Tidak bisa di gunakan setiap mau ambil absen selalu ke detect aplikasi ilegal
====================================================================================================
Review by Zikra Aulia:
Rating: 1
Content: Tolong di perbaiki lagi untuk absensi nya nggak bisa di gunakan
====================================================================================================
Review by Rasilvi:
Rating: 1
Content: error gak bisa dibuka, katanya disuruh bersihkan riwayat untuk dipulihkan
====================================================================================================
Review by ratna juwita:
Rating: 1
Content: Lelet, kalau ngga IPhone ngga bisa isi absen,, kamera mirror bikin wajah tempang
====================================================================================================
Review by Nikita zahra wilman:
Rating: 1
Content: Aplikasinya lelet, jd ga bisa ambil absen
====================================================================================================
Review by Muhammad Iqbal:
Rating: 1
Content: apk bug,nda bisa masukkk,padahal sandi udh benerr
====================================================================================================
Review by Sapu Ijuk:
Rating: 1
Content: setiap ambil absen selalu kedetek aplikasi ilegal dan endingnya tidak bisa digunakan
====================================================================================================
Review by Vitra_ Wijaya:
Rating: 1
Content: Performa aplikasi buruk,banyaknya bug,dan kualitas sisten yang buruk
====================================================================================================
Review by Dwi Aulia fitri:
Rating: 1
Content: Bagi saya ini sangat mempersulit mahasiswa untuk mengambil absen, sangat banyak kendala
====================================================================================================
Review by Sok Tau lu:
Rating: 1
Content: Banyak bug, hingga menyusuahkan mahasiswa untuk mengambil absen
====================================================================================================
Review by Muhammad faiz Al fauzi:
Rating: 1
Content: ini saya absen knapa konfirmasi trus katanya, absen saya Alfa jadinya, mending e learning aja
====================================================================================================
Review by Abielo Fritzie:
Rating: 1
Content: Saran kembali keelearning ajh min , absen disini susah , koordinatnya berubah"
====================================================================================================
Review by Faridz Siregar:
Rating: 1
Content: Aplikasi nya belum bisa berjalan min
====================================================================================================
Review by indah febriani:
Rating: 1
Content: Perbaiki apknya, tidak bsa mengambil absen.
====================================================================================================
Review by Arif Ganteng:
Rating: 1
Content: Sangat canggih tanpa bug
====================================================================================================
Review by Saica 29:
Rating: 1
Content: Lelet, sinyal bagus tapi lelet
====================================================================================================
Review by Malaz:
Rating: 1
Content: Absensi tidak jelas, khusus iPhone apalah
====================================================================================================
Review by Ahmad Mghfrn:
Rating: 5
Content: saya mohon ke pihak UNP saya ingin LMS diganti ke elearning unp saja bapak soalnya berat jika makai smile unp, kasihan bagi orng yg hp nya masih spek rendah pak ngeleg ngeleg parah bapak saya mohon pak🙏🙏
====================================================================================================
Review by Ress:
Rating: 1
Content: Ngak mau ke ambil absen padahal jaringan bagus
====================================================================================================
Review by Ridho Marnas:
Rating: 5
Content: Udah bagus daripada sebelum nya, terimakasih untuk kemudahan nya min
====================================================================================================
Review by Imam 1204:
Rating: 1
Content: Kamera tidak muncul saat mau ambil absen, tolong diperbaiki lagi bug nya, bukannya mempermudah yang ada malah mempersulit untuk absen
====================================================================================================
Review by Cava Eldaza:
Rating: 1
Content: Tolong ya tidak semua hp punya sistem yg tinggi msih ad hp mahasiswa yg sistem hp nya rendah tidak bisa menggunakan apk ini, tidak mungkin saya harus meminjam hp teman terus untuk menggunakan apk ini. Klau tidak bisa minimal kasih beasiswa kek biar biaa beli hp baru, saya sudah daftar beasiswa ini itu nga pernah loloss, maaf jdi curhatt, dah mhon segera di perbaiki apk, kdng jga suka ngelag.
====================================================================================================
Review by maulana Sajid:
Rating: 1
Content: Gajelass sok modern mana ngelag mlu tiba" hadir sendiri, sgla miror jelekkk bett, mending balik lagi ke elearning dah klo masih belum paham pengaplikasian jan sok boy
====================================================================================================
Review by Melkhi Rahman candra:
Rating: 1
Content: Tidak bisa digunakan, sering error
====================================================================================================
Review by Rizq.`々:
Rating: 1
Content: jarak kelas 151 meter, apa apaan ini dawg😭🙏
====================================================================================================
Review by annisa sayla s:
Rating: 1
Content: ribet, kembalikan elearning tercinta
====================================================================================================
Review by Tolong lah:
Rating: 1
Content: Aplikasi parahh gk bisa di akses
====================================================================================================
Review by Rivano Henda:
Rating: 1
Content: Sering bug lokasinya
====================================================================================================
Review by Vivo Y50:
Rating: 1
Content: apk nya jelek sekali, kamera ku ke balik😭
====================================================================================================
Review by Asep Kneddy:
Rating: 1
Content: jelek bet, jelek bet. tolong di perbaiki. tolong kalau gaa kuat jangan di paksa
====================================================================================================
Review by Davit Zarly:
Rating: 1
Content: Minta tolong di perbaiki dengan segera dan cepat "Device Yang Anda Gunakan Terdeteksi Menggunakan Aplikasi Illegal dan Developers Mode Aktif Safe : false DevMode : true"
====================================================================================================
Review by Rahmad Agus:
Rating: 1
Content: kamera gabisa dibuka terpaksa isi absen pakai hp teman
====================================================================================================
Review by Serly Marliza:
Rating: 1
Content: Kadang loadingnya lama
====================================================================================================
Review by Dinda Putri Adilla:
Rating: 1
Content: Gak bisa ambil absen katanya apk illegal, merugikan mahasiswa kalau gini, gimana absensi kami?
====================================================================================================
Review by Muhammad Yusuf:
Rating: 1
Content: semenjak memakai my unp Alhamdulillah tambah sulit
====================================================================================================
Review by Jeremy Kevin:
Rating: 5
Content: aplikasi yang mudah di gunakan
====================================================================================================
Review by Diah Ayu Febriana:
Rating: 2
Content: my unp tidak berfungsi dibeberapa hp
====================================================================================================
Review by Mhd Fikri Cf:
Rating: 1
Content: LOADINGGGG TEROSSSS GAJELAS APLIKASI BETA MASIH DI PAKSAIN
====================================================================================================
Review by Mhd Ikhsan s:
Rating: 4
Content: Aplikasi sering ngebug
====================================================================================================
Review by Febryo Ryo:
Rating: 1
Content: Aplikasinya sering eror
====================================================================================================
Review by Habibillah alva Putra:
Rating: 1
Content: gabisa absen pagi wei
====================================================================================================
Review by Junaidi Indrawadi:
Rating: 5
Content: Aplikasi ini cukup mudah diakses dan digunakan
====================================================================================================
Review by RAMADANI FITRIYAH HARAHAP:
Rating: 3
Content: Aplikasinya sangat susah digunakan pak, lagi sangat terknedala dalam jaringan
====================================================================================================
Review by Smart Brain:
Rating: 1
Content: Aplikasi aneh, udah pandang kasta gak berfungsi lagi. Awokwok
====================================================================================================
Review by Ah Tong:
Rating: 5
Content: Kepada teman teman sekalian jangan kasih bintang 1 nanti aplikasinya diberhentikan play store, karena biaya membuat aplikasinya juga tidak murah teman teman
====================================================================================================
Review by nan a:
Rating: 1
Content: loading nya upload nya lama sampe berjam" dan suka ngebug pak , saya jadinya absen karena itu pak
====================================================================================================
Review by Jacob Nainggolan:
Rating: 3
Content: aplikasi nya bagus namun sangat susah untuk login, padahal jaringan bagus🙏
====================================================================================================
Review by Zoom Acc:
Rating: 1
Content: apk bgus,klo udh gda bug tapi,msih bnyak bug,org ksusahan ambil absen jdnya
====================================================================================================
Review by Muhammad Ar Raffi:
Rating: 1
Content: ke detec ilegal pak jdi tidak bisa di gunakan, dan waktu di hapus dan download lagi apk nya ga bisa di buka pak
====================================================================================================
Review by Joni Jonanthan:
Rating: 1
Content: Mending hapus aja. Balikin ke e-learning
====================================================================================================
Review by Pratama Respect:
Rating: 5

In [5]:
# konversi hasil scraping ke bentuk dataframe
import pandas as pd

df = pd.DataFrame(result)
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,878e522e-1a4a-4a0d-bee4-be91e9ffa232,dinda amalia,https://play-lh.googleusercontent.com/a/ACg8oc...,"jujur ribet bgt aplikasinya, lelet, kamera mir...",1,43,1.0.94,2025-02-14 02:52:44,None,None,1.0.94
1,b2703f2f-5ec8-437c-a3c0-8718d23b1ae0,Akami Sayuri,https://play-lh.googleusercontent.com/a-/ALV-U...,"Saran saya, harusnya di uji coba dulu baru di ...",1,16,1.0.94,2025-02-20 01:38:11,None,None,1.0.94
2,71c6bbbb-23e0-4591-8bd6-542366bd2a6e,Hamid Awaludin,https://play-lh.googleusercontent.com/a-/ALV-U...,Mengecewakan. Sebaiknya sebelum diterapkan sis...,1,18,1.0.94,2025-02-13 00:55:26,None,None,1.0.94
3,2ea804f4-82de-4dbc-b9c4-02feaf1f92d5,Jeise Gaming,https://play-lh.googleusercontent.com/a/ACg8oc...,"banyak bug tolong diperbaiki minnnnnnn, gabisa...",1,39,1.0.94,2025-02-08 06:45:35,None,None,1.0.94
4,e07e779b-6650-4c79-a091-541f56137fdd,Ahmad Nur Hafidz,https://play-lh.googleusercontent.com/a-/ALV-U...,ada kesalahan dalam aplikasi yang membuat saya...,1,6,1.0.96,2025-03-12 19:45:33,None,None,1.0.96

In [6]:
# memilih baris yang akan digunakan untuk analisis
data_review = df[['reviewId', 'content', 'score']]
data_review.head()

,reviewId,content,score
0,878e522e-1a4a-4a0d-bee4-be91e9ffa232,"jujur ribet bgt aplikasinya, lelet, kamera mir...",1
1,b2703f2f-5ec8-437c-a3c0-8718d23b1ae0,"Saran saya, harusnya di uji coba dulu baru di ...",1
2,71c6bbbb-23e0-4591-8bd6-542366bd2a6e,Mengecewakan. Sebaiknya sebelum diterapkan sis...,1
3,2ea804f4-82de-4dbc-b9c4-02feaf1f92d5,"banyak bug tolong diperbaiki minnnnnnn, gabisa...",1
4,e07e779b-6650-4c79-a091-541f56137fdd,ada kesalahan dalam aplikasi yang membuat saya...,1

In [12]:
# save final result ke csv
data_review.to_csv("myunp_reviews.csv", index = False)